services:
  avogadro:
    build: .
    image: avogadro-browser
    ports:
      - "6080:6080"
    volumes:
      - ./molecules:/root/molecules
    # GPU support examples:
    # ---------------------
    # Intel / AMD GPU:
    # devices:
    #   - /dev/dri:/dev/dri
    #
    # NVIDIA GPU:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always
