[supervisord]
nodaemon=true
user=root

[program:tigervnc]
# Set default geometry to 1920x1080
command=/usr/bin/Xtigervnc :1 -desktop Avogadro -rfbport 5900 -SecurityTypes None -AlwaysShared -AcceptKeyEvents -AcceptPointerEvents -AcceptSetDesktopSize -geometry 1920x1080 -depth 24
autorestart=true

[program:openbox]
command=/usr/bin/openbox --display :1
autorestart=true
depends_on=tigervnc

[program:novnc]
command=/opt/noVNC/utils/novnc_proxy --vnc localhost:5900 --listen 6080 --web /opt/noVNC
autorestart=true
depends_on=tigervnc

[program:avogadro]
# Use the new startup script
command=/usr/local/bin/start-avogadro.sh
environment=DISPLAY=":1"
autorestart=false
depends_on=openbox
